# Generated by Django 5.1.7 on 2025-04-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_card_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_by',
        ),
    ]
